# common是必须的section
[common]
server_addr = "127.0.0.1"
bind_port = 7000
log_file = "./frpc.log"
# debug, info, warn, error
log_level = "info"
# file, console
log_way = "file"

# test1即为name
[test1]
passwd = "123"
local_port = "22"