# common是必须的section
[common]
bind_addr = "0.0.0.0"
bind_port = 17000
log_file = "./frps.log"
# debug, info, warn, error
log_level = "info"
# file, console
log_way = "file"

[client]
    # test1即为name
    [client.test1]
    passwd = "123"
    bind_addr = "0.0.0.0"
    listen_port = 6000

    [client.test2]
    passwd = "1234"
    bind_addr = "0.0.0.1"
    listen_port = 7000